USE CarMarket;

CREATE TABLE IF NOT EXISTS CarWarehouse (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    price INT NOT NULL ,
    year INT NOT NULL ,
    make VARCHAR(20) NOT NULL ,
    model VARCHAR(20) NOT NULL ,
    trim VARCHAR(50) NOT NULL ,
    location VARCHAR(50) NOT NULL ,
    mileage INT NOT NULL ,
    image VARCHAR(1000) ,
    url_id UNSIGNED BIGINT ,
    last_update VARCHAR(50) ,
    description VARCHAR(2000) ,
    seller_name VARCHAR(100) ,
    seller_year_joined INT ,
    warning BOOLEAN DEFAULT FALSE ,
    transmission VARCHAR(20) ,
    fuel VARCHAR(20) ,
    exterior_color VARCHAR(15) ,
    interior_color VARCHAR(15) ,
    horse_power INT ,
    engine_size DECIMAL(2,1) ,
    number_of_owner VARCHAR(2) ,
    sold BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (url_id),
    KEY `year` (year),
    KEY `price` (price),
    KEY `make` (make),
    KEY `model` (model),
    KEY `mileage` (mileage),
    KEY `location` (location),
    KEY `createdAt` (createdAt),
    KEY `updatedAt` (updatedAt)
)